apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: networking
spec:
  encryptedData:
    CLOUDFLARE_API_TOKEN: AgCeEMt9zztp+/R7sEorXh8H2ZEM6D6h/HDexsufNafeT3m/TF63wyDJOpxjguQ0I0L4+zJGyfbCQz0R9tpHuHBVRn2BGMuOnVWj1ep2L5HCMnWASTvSIkYR/9NJzE/gWjHOKbM40EKp0m2tEEJJkkDqerzZsoqars2vzVIVRng5g7TMHgQ0TulcbhvTP5ibC2KP/U9ovEwEHh2g7Puvu2Pyo8JBJq17YK3UOtizTKlPEv6kaL/wzbofC3vRXemkeKmUS1UzdJ20yICAyyOHGSrRmCylk7wMxUixqzKbXcrc4B7+w2oCSUg5PVAzw45b12ObVCJE4EWU019yu0eYzduH7UVWFR+FkQC2OcJS+58/4L/iB/ZfykaJARi9bSS/uc0rN7/I0GRIouXfK6ZQZmoNb6QxCjjQhv6J+1dBbKLRHOOV4dtbNM+N7wasKr5CBGpHhdTLt+qRCBe1169T6mpS6aJWnxYIXAb9OQXSPOGoQWhvbvjJ0nuDFU9Fehr56tdaSTcwjqXikmrn0YmSXrrM76oymoDiUA+ICzBPxBHVNvraAQGRFjyHELhr7IdjljYQPnt7dKsYglY286rsG3fogzCjzTF/b5edVfsDenQ8iuVbflIeiz1nFI79Rll/9KKuTS3IfmRd3gV2ALX2+I/cRIcXkMGHDtvNJtOCFY6ZAuwTUcfDpVkHGeiJSvsuEWpMsvVRh0KmpTxoZKx6LSmMcVo5qu619ZRDXK1C0gxMMy8JcTQVxRDd
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: networking

