apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: default
spec:
  encryptedData:
    CLOUDFLARE_API_TOKEN: AgA0ThAkMgDIoY3XrREYuxd9FVwWc2aUumceK9NiH7kY+lHhvFMKvitKa7gYM+m13uSbAdxpYKW/ZJXvP0sPmmaoBTWgOO/98aWLi2yeyYBiG8bT7TVTR4KoasvWVC1Qe9tNbbv6oporinqNh3yJp2a+hI8LCYG7vC4uLkhddOKeg6jZvHhSP3pVvKZR9Cc6MeKAh1kxkwEV1OOoIkrcFbCSfePpep6C58bCE01SYhDjYrK7wXUAZGHbY9OpbkZRr2IkB/ZvA8CmwH0iQbAVSTFBVW8M3XvGVjkaDBNzN/EyF7MhMRL6Q5CmpvUUbu9WyJAGQ0R0OSyvFwZU4gjsDtx9f5tMpDOpnsK/NwO3/H+/kEMJAkGgWg2IXfyKjkRrZzh5aQRTy2FfSKAlm1/y7onQFIsS30514YZRlkTb+NReE/vX1WNingwaKXjD7110w3dgNG4MvGVBfKth2+XoxP1H23QNE42t/BqTh2JOL2TT6aMxSh9Z/sr9fr7ulZahYhAABAtzv0+7ExPDa0VPAti6iTkG573aP1lEo7lyRKofIunVyoiIxWkGnQUfaJN63rjUgjjxgbrnUcL3hrVIGRrXcHrDpc2+mcqMXL6sIIld23ia2LldTRGJenhORwuH6HR29OiFhoYT5naCQQaHTw/UqNGoB2+Y9fJfr76MP93roIpJbYzqbQPsvLSBQ8FN5vgnGIRCReMrCRGLNfMOdqMRL8g8mktnWhYps9aHezUIcYfT5oX12U32
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: default

