---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cloudflare-ddns
  namespace: flux-system
spec:
  path: ./kubernetes/apps/networking/cloudflare-ddns/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cloudflare-ddns
      namespace: networking
  interval: 30m
  retryInterval: 1m
  timeout: 3m