---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: '4.5.2'
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
        namespace: flux-system
  values:
    controller:
      replicaCount: 3
      watchIngressWithoutClass: true
      ingressClassResource:
        default: true
      service:
        annotations:
          metallb.universe.tf/loadBalancerIPs: 192.168.181.2
      resources:
        requests:
          cpu: 64m
          memory: 128Mi
        limits:
          cpu: 128m
          memory: 200Mi
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
      - key: "arch"
        operator: "Equal"
        value: "arm64"
    service:
      spec:
        externalTrafficPolicy: Cluster