---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: '0.13.9'
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
  install:
    createNamespace: true
  values:
    speaker:
      resources:
        requests:
          cpu: 5m
          memory: 32Mi
        limits:
          cpu: 15m
          memory: 48Mi
      tolerations:
        - key: arch
          operator: Equal
          value: arm64
    controller:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 20m
          memory: 50Mi
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
      - key: arch
        operator: Equal
        value: arm64