apiVersion: apps/v1
kind: Deployment
metadata:
        name: kube101
        namespace: default
spec:
        replicas: 2
        selector:
                matchLabels:
                        app: kube101
        template:
                metadata:
                        labels:
                                app: kube101
                spec:
                        containers:
                        - name: kube101
                          image: geerlingguy/kube101:intro
                          ports:
                                  - containerPort: 80
                          livenessProbe:
                                  httpGet:
                                          path: /
                                          port: 80
                          readinessProbe:
                                  httpGet:
                                          path: /
                                          port: 80
                        tolerations:
                        - key: arch
                          operator: "Equal"
                          value: "arm64"
                          effect: "NoSchedule"