---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx-ingress
  namespace: flux-system
spec:
  path: ./kubernetes/apps/networking/nginx-ingress/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: nginx-ingress
      namespace: ingress-nginx
  interval: 30m
  retryInterval: 1m
  timeout: 3m