---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-provisioner
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: '4.0.17'
      sourceRef:
        kind: HelmRepository
        name: nfs-provisioner
        namespace: flux-system
  values:
    replicaCount: 3
    storageClass:
      name: nfs-client
      defaultClass: true
      provisionerName: local/nfs-storage
      archiveOnDelete: true
      pathPattern: "${.PVC.namespace}-${.PVC.name}"
    nfs:
      server: kube-storage
      path: "/data/kubernetes"
    nodeSelector:
      node-role.kubernetes.io/control-plane: ""
    resources:
      requests:
        cpu: 10m
        memory: 25Mi
      limits:
        cpu: 25m
        memory: 50Mi
    tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
    - key: arch
      operator: Equal
      value: arm64