---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metrics-server
      version: '3.8.3'
      sourceRef:
        kind: HelmRepository
        name: metrics-server-charts
        namespace: flux-system
  install:
    createNamespace: true
  values:
    replicas: 2
    tolerations:
      - key: node-role.kubernetes.io/control-plane
      - key: arch
        operator: Equal
        value: "arm64"
    args:
      - "--kubelet-insecure-tls=true"
      - "--requestheader-client-ca-file"